from enum import IntEnum


class MoveType(IntEnum):
    FORWARD = 1
    BACKWARD = 2
    LEFT = 4
    RIGHT = 8
    DIAGONAL = 16
    L_SHAPE = 32


PAWN_DAMAGE = 5
PAWN_HEALTH = 10
PAWN_NAME = "Pawn"
PAWN_MOVE_RANGE = 1
PAWN_MOVE_TYPE = MoveType.FORWARD

BISHOP_DAMAGE = 15
BISHOP_HEALTH = 30
BISHOP_NAME = "Bishop"
BISHOP_MOVE_RANGE = 8
BISHOP_MOVE_TYPE = MoveType.DIAGONAL

KNIGHT_DAMAGE = 15
KNIGHT_HEALTH = 30
KNIGHT_NAME = "Knight"
KNIGHT_MOVE_RANGE = 1
KNIGHT_MOVE_TYPE = MoveType.L_SHAPE

ROOK_DAMAGE = 25
ROOK_HEALTH = 50
ROOK_NAME = "Rook"
ROOK_MOVE_RANGE = 8
ROOK_MOVE_TYPE = (
    MoveType.FORWARD
    | MoveType.BACKWARD
    | MoveType.LEFT
    | MoveType.RIGHT
)

QUEEN_DAMAGE = 45
QUEEN_HEALTH = 90
QUEEN_NAME = "Queen"
QUEEN_MOVE_RANGE = 8
QUEEN_MOVE_TYPE = (
    MoveType.FORWARD
    | MoveType.BACKWARD
    | MoveType.LEFT
    | MoveType.RIGHT
    | MoveType.DIAGONAL
)

KING_DAMAGE = 10
KING_HEALTH = 80
KING_NAME = "King"
KING_MOVE_RANGE = 1
KING_MOVE_TYPE = (
    MoveType.FORWARD
    | MoveType.BACKWARD
    | MoveType.LEFT
    | MoveType.RIGHT
    | MoveType.DIAGONAL
)
