BOARD_ROW_SIZE = 8
BOARD_COL_SIZE = 8

PAWN_DAMAGE = 5
PAWN_HEALTH = 10
PAWN_NAME = "Pawn"
PAWN_RANGE = 1
PAWN_VALUE = 1

BISHOP_DAMAGE = 15
BISHOP_HEALTH = 30
BISHOP_NAME = "Bishop"
BISHOP_RANGE = 8
BISHOP_VALUE = 3

KNIGHT_DAMAGE = 15
KNIGHT_HEALTH = 30
KNIGHT_NAME = "Knight"
KNIGHT_RANGE = 1
KNIGHT_VALUE = 3

ROOK_DAMAGE = 25
ROOK_HEALTH = 50
ROOK_NAME = "Rook"
ROOK_RANGE = 8
ROOK_VALUE = 5

QUEEN_DAMAGE = 45
QUEEN_HEALTH = 90
QUEEN_NAME = "Queen"
QUEEN_RANGE = 8
QUEEN_VALUE = 9

KING_DAMAGE = 10
KING_HEALTH = 80
KING_NAME = "King"
KING_RANGE = 1
KING_VALUE = 100
